DROP DATABASE IF EXISTS css_db;

CREATE DATABASE css_db;

USE css_db;

CREATE TABLE css (
  id INT(255) NOT NULL,
  que TEXT NOT NULL,
  a VARCHAR(222) NOT NULL,
  b VARCHAR(222) NOT NULL,
  ans VARCHAR(222) NOT NULL
);