DROP DATABASE IF EXISTS html_db;

CREATE DATABASE html_db;

USE html_db;

CREATE TABLE html (
  id INT(255) NOT NULL,
  que TEXT NOT NULL,
  a VARCHAR(222) NOT NULL,
  b VARCHAR(222) NOT NULL,
  ans VARCHAR(222) NOT NULL
);